[profile.default]
src = "src"
test = "test"
out = "out"
libs = ["lib"]
script = "script"
solc_version = "0.8.37"
evm_version = "cancun"
optimizer = true
optimizer_runs = 1000

[fmt]
line_length = 100
